In [ ]:
# default_exp data_preparation
# default_cls_lvl 2

In [ ]:
%load_ext autotime

# Data Cleaning

> Dieser Bereich bereinigt das zuvor vereinfachte Datenset.

Wie auch beim vorherigen Modul werden nur die aus unserer Sicht wichtigsten Features bereinigt. Hier besteht noch deutlich mehr potential. Doch dieses Modul fokusiert sich auf folgende Features:
 - Age
 - Rent (renta)

In [ ]:
#export
import pandas as pd
import numpy as np

from fastscript import *

In [ ]:
#export 
def load_data(path='data/interim/01_train.csv'):
    """load data"""
    return pd.read_csv(path)

In [ ]:
train = load_data().sample(100000)

In [ ]:
train.age.describe()

count    100000.000000
mean         40.123920
std          17.299295
min          -1.000000
25%          24.000000
50%          39.000000
75%          50.000000
max         116.000000
Name: age, dtype: float64

In [ ]:
pd.set_option('display.max_columns', 60)
train.head(10)

,id,ind_empleado,pais_residencia,sexo,age,ind_nuevo,antiguedad,indrel,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,fecha_dato_month,fecha_dato_year,month_int,fecha_alta_month,fecha_alta_year,fecha_alta_day,fecha_alta_month_int,fecha_alta_day_int,ult_fec_cli_1t_month,ult_fec_cli_1t_year,ult_fec_cli_1t_day,ult_fec_cli_1t_month_int
12897665,789434,0,0,1,42,0,93,1,1,0,1,0,-1,5,0,1,45,1,33329,2,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,17,8,13,27,164,5012,1,5,1,61
2424992,935508,0,0,1,24,0,47,1,1,0,1,0,-1,1,0,1,8,1,207193,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,4,8,16,19,200,6099,1,5,1,61
799422,135926,0,0,1,61,0,193,1,1,1,1,0,-1,5,0,1,28,0,-1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2,6,4,22,54,1662,1,5,1,61
12779651,518827,0,0,0,46,0,106,1,1,1,1,0,-1,28,0,1,28,0,50559,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,17,2,10,21,122,3731,1,5,1,61
2926487,101440,0,0,0,77,0,204,1,1,0,1,0,-1,5,0,1,3,1,142356,2,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,5,0,5,7,3,7,43,1312,1,5,1,61
8942773,1496261,0,0,1,20,1,1,1,1,0,1,0,-1,157,0,1,28,0,-1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,12,11,20,2,251,7632,1,5,1,61
12633110,1211577,0,0,0,23,0,29,1,1,0,1,0,-1,1,0,1,36,1,62405,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,16,10,18,30,226,6900,1,5,1,61
8085457,1050227,0,0,1,25,0,39,1,1,1,1,0,-1,1,0,1,45,0,77098,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,11,8,17,10,212,6455,1,5,1,61
6894919,105524,0,15,1,51,0,205,1,1,1,0,1,-1,5,0,1,-1,0,-1,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,10,9,3,18,45,1383,1,5,1,61
12042931,122484,0,0,1,72,0,201,1,1,0,1,0,-1,71,1,1,28,0,177150,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,16,5,4,12,53,1622,1,5,1,61

## clean_age

In [ ]:
#export
def clean_age(df:pd.DataFrame):
    """clean age"""
    df.loc[df.age < 18,"age"]  = (df.loc[(df.age >= 18) & (df.age <= 30),"age"].mean(skipna=True))
    df.loc[df.age > 100,"age"] = (df.loc[(df.age >= 30) & (df.age <= 100),"age"].mean(skipna=True))
    df["age"].fillna(df["age"].mean(),inplace=True)
    df["age"] = df["age"].astype(int)
    return df

In [ ]:
train.age.describe()

count    100000.000000
mean         40.123920
std          17.299295
min          -1.000000
25%          24.000000
50%          39.000000
75%          50.000000
max         116.000000
Name: age, dtype: float64

In [ ]:
df1 = clean_age(train)
assert df1.age.min() >= 18
assert df1.age.max() <= 100

print("#### before ####")
print(train.age.describe())

print("#### after ####")
print(df1.age.describe())
#del df1

#### before ####
count    100000.000000
mean         40.217120
std          16.978013
min          18.000000
25%          24.000000
50%          39.000000
75%          50.000000
max         100.000000
Name: age, dtype: float64
#### after ####
count    100000.000000
mean         40.217120
std          16.978013
min          18.000000
25%          24.000000
50%          39.000000
75%          50.000000
max         100.000000
Name: age, dtype: float64

In [ ]:
df1.head(10)

,id,ind_empleado,pais_residencia,sexo,age,ind_nuevo,antiguedad,indrel,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,fecha_dato_month,fecha_dato_year,month_int,fecha_alta_month,fecha_alta_year,fecha_alta_day,fecha_alta_month_int,fecha_alta_day_int,ult_fec_cli_1t_month,ult_fec_cli_1t_year,ult_fec_cli_1t_day,ult_fec_cli_1t_month_int
12897665,789434,0,0,1,42,0,93,1,1,0,1,0,-1,5,0,1,45,1,33329,2,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,17,8,13,27,164,5012,1,5,1,61
2424992,935508,0,0,1,24,0,47,1,1,0,1,0,-1,1,0,1,8,1,207193,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,4,8,16,19,200,6099,1,5,1,61
799422,135926,0,0,1,61,0,193,1,1,1,1,0,-1,5,0,1,28,0,-1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2,6,4,22,54,1662,1,5,1,61
12779651,518827,0,0,0,46,0,106,1,1,1,1,0,-1,28,0,1,28,0,50559,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,17,2,10,21,122,3731,1,5,1,61
2926487,101440,0,0,0,77,0,204,1,1,0,1,0,-1,5,0,1,3,1,142356,2,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,5,0,5,7,3,7,43,1312,1,5,1,61
8942773,1496261,0,0,1,20,1,1,1,1,0,1,0,-1,157,0,1,28,0,-1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,12,11,20,2,251,7632,1,5,1,61
12633110,1211577,0,0,0,23,0,29,1,1,0,1,0,-1,1,0,1,36,1,62405,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,16,10,18,30,226,6900,1,5,1,61
8085457,1050227,0,0,1,25,0,39,1,1,1,1,0,-1,1,0,1,45,0,77098,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,11,8,17,10,212,6455,1,5,1,61
6894919,105524,0,15,1,51,0,205,1,1,1,0,1,-1,5,0,1,-1,0,-1,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,10,9,3,18,45,1383,1,5,1,61
12042931,122484,0,0,1,72,0,201,1,1,0,1,0,-1,71,1,1,28,0,177150,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,16,5,4,12,53,1622,1,5,1,61

## clean_renta

In [ ]:
#export
def clean_renta(df:pd.DataFrame):
    """fill in NaNs with median value from its region"""
    df = df[df["renta"] > 0].copy()
    grouped = df.groupby("cod_prov").agg({"renta":lambda x: x.median(skipna=True)}).reset_index()
    new_incomes = pd.merge(df,grouped,how="inner",on="cod_prov").loc[:, ["cod_prov","renta_y"]]
    new_incomes = new_incomes.rename(columns={"renta_y":"renta"}).sort_values("renta").sort_values("cod_prov")
    df.sort_values("cod_prov",inplace=True)
    df = df.reset_index()
    new_incomes = new_incomes.reset_index()

    df.loc[df.renta < 0,"renta"] = new_incomes.loc[df.renta.isnull(),"renta"].reset_index()
    df.loc[df.renta < 0,"renta"] = df.loc[df.renta.notnull(),"renta"].median()
    df['renta'] = df['renta'].astype(np.int32)
    df.sort_values(by="month_int",inplace=True)
    df.drop('index', inplace=True, axis=1)
    return df

In [ ]:
df1 = clean_renta(train)

In [ ]:
assert df1.renta.min() > 0

print("#### before ####")
print(train.renta.describe())

print("#### after ####")
print(df1.renta.describe())

del df1

#### before ####
count    1.000000e+05
mean     1.067759e+05
std      2.371295e+05
min     -1.000000e+00
25%      4.121675e+04
50%      8.322900e+04
75%      1.369455e+05
max      2.889440e+07
Name: renta, dtype: float64
#### after ####
count    7.944200e+04
mean     1.344076e+05
std      2.589748e+05
min      4.559000e+03
25%      6.846575e+04
50%      1.014830e+05
75%      1.559040e+05
max      2.889440e+07
Name: renta, dtype: float64

In [ ]:
#export
@call_parse
def clean_all_data(source:Param("source csv file", str) = 'data/interim/01_train.csv',
                   dest:Param("destination csv file", str) = 'data/interim/02_train.csv'):
    """main function to clean all data"""
    data = load_data(source)
    data = clean_age(data)
    data = clean_renta(data)
    data.to_csv(dest, index=False)
    return data

In [ ]:
train = clean_all_data()

In [ ]:
from nbdev.export import *
notebook2script()

Converted 01_data_preprocess.ipynb.
Converted 02_data_Cleaning.ipynb.
Converted 03_target_vars.ipynb.
Converted 04_base_model.ipynb.
Converted index.ipynb.