In [ ]:
%load_ext autotime
%load_ext autoreload
%autoreload 2

# Distributed Machine Learning

Eines der grössten Schwierigkeiten ist es passende ML Algorithmen zu finden. Die meisten Algorithmen werden aus Performancegründen in C, C++ oder ähnlichne Sprachen geschrieben. R und Python sind für die Entwicklung von Algorithmen ungeeignet. Um dennoch aufzuzigen, dass Federeated Learning einen Mehrwert bringt werden wir ein Cluster von Docker Containern aufbauen. Dieser Cluster besteht aus 2 Worker Nodes und einem Master Node. Gesteuert werden diese mit [Open MPI](https://www.open-mpi.org/) (Open Source High Performance Computing - Library). MPI wird von XGBoost als auch von Microsofts LightGBM unterstützt. Letzteres verwenden wir an dieser Stelle, da die Implementierung sich weniger Komplex gestaltet.

## LightGBM
[LigthGBM Distributed Learning](https://github.com/microsoft/LightGBM/blob/master/docs/Parallel-Learning-Guide.rst)

## Data Preparation

In [ ]:
#export
import lightgbm as lgb
import numpy as np
import pandas as pd

from community_learning import base_model
from community_learning import features
from itertools import compress
from community_learning.example import get_prediction, evaluate_predictions, get_two_region_data

In [ ]:
data = get_two_region_data()

load data
prepare data

In [ ]:
data.keys()

dict_keys(['product_dict', 'product_reverse_dict', 'feature_cols', 'target_cols', 'train', 'test', 'train_south', 'train_north', 'train_X_south', 'train_y_south', 'train_X_north', 'train_y_north', 'train_X', 'train_y', 'test_south', 'test_north'])

In [ ]:
#we prepare the data in one csv file where y is the label column
export_cols = data['feature_cols'].copy()
export_cols += ['y']

train = data['train']
train_south = train.loc[train.region == 'south',]
train_north = train.loc[train.region == 'north',]
train[export_cols].to_csv('data/final/data_lightgbm/train.csv', index = False)
train_south[export_cols].to_csv('data/final/data_lightgbm/train_south.csv', index = False)
train_north[export_cols].to_csv('data/final/data_lightgbm/train_north.csv', index = False)

time: 3.57 s

In [ ]:
valid = pd.read_csv('data/final/data_lightgbm/validation.csv')
valid = base_model.encode_products(valid)
valid[export_cols].to_csv('data/final/data_lightgbm/validation_enc.csv', index = False)

time: 176 ms

## train_community.conf
```
task = train
valid_data = validation_enc.csv
boosting_type = gbdt
objective = multiclass
num_class = 22
eta = 0.05
min_child_weight = 1
#subsample = 0.7
subsample = 1
colsample_bytree = 0.7
max_depth = 8
metric = multi_logloss
metric_freq = 1
is_training_metric = true
num_trees = 50
data = train.csv
header = true
label_column = name:y
machine_list_file = mlist.txt
num_machines = 2
tree_learner = data
seed = 0
#num_threads = 1
output_model = model.txt
```


## run cluster training
```
mpiexec --machinefile mlist.txt -npernode 1  ./lightgbm config=train.conf
```

In [ ]:
train_org, test = base_model.load_data()
product_dict = base_model.get_product_dict(train_org)
product_reverse_dict = base_model.get_product_reverse_dict(train_org)

In [ ]:
data = get_two_region_data()

load data
prepare data

In [ ]:
bst = lgb.Booster(model_file='data/final/data_lightgbm/model.txt')
preds = bst.predict(data['test'][base_model.feature_cols])

In [ ]:
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = test.copy()
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision single node all data = {test_data['apk'].mean()}")

mean average precision single node all data = 0.022738471706301475
time: 1min 2s

In [ ]:
bst = lgb.Booster(model_file='data/final/data_lightgbm/model_north.txt')
preds = bst.predict(test[base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = test.copy()
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision single node north = {test_data['apk'].mean()}")

mean average precision single node north = 0.022714324920308386

In [ ]:
bst = lgb.Booster(model_file='data/final/data_lightgbm/model_south.txt')
preds = bst.predict(test[base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = test.copy()
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision single node south = {test_data['apk'].mean()}")

mean average precision single node south = 0.02279485233961093

In [ ]:
data

{'product_dict': {'ind_cco_fin_ult1': 0,
  'ind_cder_fin_ult1': 1,
  'ind_cno_fin_ult1': 2,
  'ind_ctju_fin_ult1': 3,
  'ind_ctma_fin_ult1': 4,
  'ind_ctop_fin_ult1': 5,
  'ind_ctpp_fin_ult1': 6,
  'ind_deco_fin_ult1': 7,
  'ind_dela_fin_ult1': 8,
  'ind_deme_fin_ult1': 9,
  'ind_ecue_fin_ult1': 10,
  'ind_fond_fin_ult1': 11,
  'ind_hip_fin_ult1': 12,
  'ind_nom_pens_ult1': 13,
  'ind_nomina_ult1': 14,
  'ind_plan_fin_ult1': 15,
  'ind_pres_fin_ult1': 16,
  'ind_reca_fin_ult1': 17,
  'ind_recibo_ult1': 18,
  'ind_tjcr_fin_ult1': 19,
  'ind_valo_fin_ult1': 20,
  'ind_viv_fin_ult1': 21},
 'product_reverse_dict': {0: 'ind_cco_fin_ult1',
  1: 'ind_cder_fin_ult1',
  2: 'ind_cno_fin_ult1',
  3: 'ind_ctju_fin_ult1',
  4: 'ind_ctma_fin_ult1',
  5: 'ind_ctop_fin_ult1',
  6: 'ind_ctpp_fin_ult1',
  7: 'ind_deco_fin_ult1',
  8: 'ind_dela_fin_ult1',
  9: 'ind_deme_fin_ult1',
  10: 'ind_ecue_fin_ult1',
  11: 'ind_fond_fin_ult1',
  12: 'ind_hip_fin_ult1',
  13: 'ind_nom_pens_ult1',
  14: 'ind_nomina_ult1',
  15: 'ind_plan_fin_ult1',
  16: 'ind_pres_fin_ult1',
  17: 'ind_reca_fin_ult1',
  18: 'ind_recibo_ult1',
  19: 'ind_tjcr_fin_ult1',
  20: 'ind_valo_fin_ult1',
  21: 'ind_viv_fin_ult1'},
 'feature_cols': ['ind_empleado',
  'sexo',
  'age',
  'renta',
  'ind_nuevo',
  'indrel',
  'indrel_1mes',
  'tiprel_1mes',
  'indresi',
  'indext',
  'conyuemp',
  'indfall',
  'tipodom',
  'ind_actividad_cliente',
  'segmento',
  'antiguedad',
  'pais_residencia',
  'canal_entrada',
  'ind_cco_fin_ult1_s',
  'ind_cder_fin_ult1_s',
  'ind_cno_fin_ult1_s',
  'ind_ctju_fin_ult1_s',
  'ind_ctma_fin_ult1_s',
  'ind_ctop_fin_ult1_s',
  'ind_ctpp_fin_ult1_s',
  'ind_deco_fin_ult1_s',
  'ind_deme_fin_ult1_s',
  'ind_dela_fin_ult1_s',
  'ind_ecue_fin_ult1_s',
  'ind_fond_fin_ult1_s',
  'ind_hip_fin_ult1_s',
  'ind_plan_fin_ult1_s',
  'ind_pres_fin_ult1_s',
  'ind_reca_fin_ult1_s',
  'ind_tjcr_fin_ult1_s',
  'ind_valo_fin_ult1_s',
  'ind_viv_fin_ult1_s',
  'ind_nomina_ult1_s',
  'ind_nom_pens_ult1_s',
  'ind_recibo_ult1_s'],
 'target_cols': ['ind_ahor_fin_ult1',
  'ind_aval_fin_ult1',
  'ind_cco_fin_ult1',
  'ind_cder_fin_ult1',
  'ind_cno_fin_ult1',
  'ind_ctju_fin_ult1',
  'ind_ctma_fin_ult1',
  'ind_ctop_fin_ult1',
  'ind_ctpp_fin_ult1',
  'ind_deco_fin_ult1',
  'ind_deme_fin_ult1',
  'ind_dela_fin_ult1',
  'ind_ecue_fin_ult1',
  'ind_fond_fin_ult1',
  'ind_hip_fin_ult1',
  'ind_plan_fin_ult1',
  'ind_pres_fin_ult1',
  'ind_reca_fin_ult1',
  'ind_tjcr_fin_ult1',
  'ind_valo_fin_ult1',
  'ind_viv_fin_ult1',
  'ind_nomina_ult1',
  'ind_nom_pens_ult1',
  'ind_recibo_ult1'],
 'train':         ind_empleado  sexo  age   renta  ind_nuevo  indrel  indrel_1mes  \
 0                  3     0   56  326124          0       1            1
 1                  3     0   56  326124          0       1            1
 2                  3     0   56  326124          0       1            1
 3                  3     1   61  430477          0       1            1
 4                  3     1   61  430477          0       1            1
 ...              ...   ...  ...     ...        ...     ...          ...
 421949             0     0   45   75445          1       1            1
 421950             0     0   45   75445          1       1            1
 421951             0     0   45   75445          1       1            1
 421952             0     0   45   75445          1       1            1
 421953             0     0   45   75445          1       1            1

         tiprel_1mes  indresi  indext  ...  ind_valo_fin_ult1_s  \
 0                 0        1       0  ...                    1
 1                 0        1       0  ...                    1
 2                 0        1       0  ...                    1
 3                 0        1       0  ...                    1
 4                 0        1       0  ...                    1
 ...             ...      ...     ...  ...                  ...
 421949            0        1       0  ...                    0
 421950            0        1       0  ...                    0
 421951            0        1       0  ...                    0
 421952            0        1       0  ...                    0
 421953            0        1       0  ...                    0

         ind_viv_fin_ult1_s  ind_nomina_ult1_s  ind_nom_pens_ult1_s  \
 0                        0                  0                    0
 1                        0                  0                    0
 2                        0                  0                    0
 3                        0                  0                    0
 4                        0                  0                    0
 ...                    ...                ...                  ...
 421949                   0                  0                    0
 421950                   0                  0                    0
 421951                   0                  0                    0
 421952                   0                  0                    0
 421953                   0                  0                    0

         ind_recibo_ult1_s  month_int       id   y    nomprov  region
 0                       0          5    15889  19     MADRID   south
 1                       0         12    15889  19     MADRID   south
 2                       0         15    15889  19     MADRID   south
 3                       1          6    15892   0     MADRID   south
 4                       1          9    15892   8     MADRID   south
 ...                   ...        ...      ...  ..        ...     ...
 421949                  0         11  1454615   2  BARCELONA   north
 421950                  0         12  1454615  14  BARCELONA   north
 421951                  0         12  1454615  13  BARCELONA   north
 421952                  0         14  1454615  14  BARCELONA   north
 421953                  0         14  1454615  13  BARCELONA   north

 [421954 rows x 45 columns],
 'test':              id  ind_empleado  pais_residencia  sexo  age  ind_nuevo  \
 0         15889             3                0     0   56          0
 1         15890             1                0     0   63          0
 2         15892             3                0     1   62          0
 3         15893             0                0     0   63          0
 4         15894             1                0     0   60          0
 ...         ...           ...              ...   ...  ...        ...
 702430  1454615             0                0     0   46          0
 702431  1454616             0                0     1   21          0
 702432  1454617             0                0     1   21          0
 702433  1454618             0                0     0   20          0
 702434  1454620             0                0     0   20          0

         antiguedad  indrel  indrel_1mes  tiprel_1mes  ...  \
 0              255       1            1            0  ...
 1              256       1            1            0  ...
 2              256       1            1            0  ...
 3              256       1            1            0  ...
 4              256       1            1            0  ...
 ...            ...     ...          ...          ...  ...
 702430           8       1            1            0  ...
 702431           8       1            1            0  ...
 702432           8       1            1            0  ...
 702433           8       1            1            1  ...
 702434           8       1            1            0  ...

         ind_pres_fin_ult1_s  ind_reca_fin_ult1_s  ind_tjcr_fin_ult1_s  \
 0                         0                    0                    0
 1                         0                    0                    1
 2                         0                    1                    1
 3                         0                    0                    0
 4                         0                    1                    1
 ...                     ...                  ...                  ...
 702430                    0                    0                    0
 702431                    0                    0                    0
 702432                    0                    0                    0
 702433                    0                    0                    0
 702434                    0                    0                    0

         ind_valo_fin_ult1_s  ind_viv_fin_ult1_s  ind_nomina_ult1_s  \
 0                         1                   0                  0
 1                         0                   0                  1
 2                         1                   0                  0
 3                         1                   0                  0
 4                         1                   0                  1
 ...                     ...                 ...                ...
 702430                    0                   0                  0
 702431                    0                   0                  0
 702432                    0                   0                  0
 702433                    0                   0                  0
 702434                    0                   0                  0

         ind_nom_pens_ult1_s  ind_recibo_ult1_s    nomprov  region
 0                         0                  0     MADRID   south
 1                         1                  1     MADRID   south
 2                         0                  1     MADRID   south
 3                         0                  0     MADRID   south
 4                         1                  1     MADRID   south
 ...                     ...                ...        ...     ...
 702430                    0                  0  BARCELONA   north
 702431                    0                  0     BURGOS   north
 702432                    0                  0      CADIZ   south
 702433                    0                  0     MADRID   south
 702434                    0                  0    CACERES   north

 [702435 rows x 81 columns],
 'train_south':         ind_empleado  sexo  age   renta  ind_nuevo  indrel  indrel_1mes  \
 0                  3     0   56  326124          0       1            1
 1                  3     0   56  326124          0       1            1
 2                  3     0   56  326124          0       1            1
 3                  3     1   61  430477          0       1            1
 4                  3     1   61  430477          0       1            1
 ...              ...   ...  ...     ...        ...     ...          ...
 421937             0     1   28  118461          1       1            1
 421938             0     1   28  118461          1       1            1
 421939             0     0   41   52101          1       1            1
 421942             0     0   60   37612          1       1            1
 421947             0     0   20  175851          1       1            1

         tiprel_1mes  indresi  indext  ...  ind_valo_fin_ult1_s  \
 0                 0        1       0  ...                    1
 1                 0        1       0  ...                    1
 2                 0        1       0  ...                    1
 3                 0        1       0  ...                    1
 4                 0        1       0  ...                    1
 ...             ...      ...     ...  ...                  ...
 421937            0        1       1  ...                    0
 421938            0        1       1  ...                    0
 421939            0        1       0  ...                    0
 421942            0        1       0  ...                    0
 421947            0        1       0  ...                    0

         ind_viv_fin_ult1_s  ind_nomina_ult1_s  ind_nom_pens_ult1_s  \
 0                        0                  0                    0
 1                        0                  0                    0
 2                        0                  0                    0
 3                        0                  0                    0
 4                        0                  0                    0
 ...                    ...                ...                  ...
 421937                   0                  0                    0
 421938                   0                  0                    0
 421939                   0                  0                    0
 421942                   0                  0                    0
 421947                   0                  0                    0

         ind_recibo_ult1_s  month_int       id   y  nomprov  region
 0                       0          5    15889  19   MADRID   south
 1                       0         12    15889  19   MADRID   south
 2                       0         15    15889  19   MADRID   south
 3                       1          6    15892   0   MADRID   south
 4                       1          9    15892   8   MADRID   south
 ...                   ...        ...      ...  ..      ...     ...
 421937                  1         14  1454555  14   MADRID   south
 421938                  1         14  1454555  13   MADRID   south
 421939                  0         11  1454583  18   MURCIA   south
 421942                  0         10  1454606  18  SEVILLA   south
 421947                  0         10  1454608   0   MADRID   south

 [278334 rows x 45 columns],
 'train_north':         ind_empleado  sexo  age   renta  ind_nuevo  indrel  indrel_1mes  \
 40                 2     0   52  130903          0       1            1
 41                 2     0   52  130903          0       1            1
 186                0     0   57  215210          0       1            1
 188                0     1   68  195763          0       1            1
 189                0     1   68  195763          0       1            1
 ...              ...   ...  ...     ...        ...     ...          ...
 421949             0     0   45   75445          1       1            1
 421950             0     0   45   75445          1       1            1
 421951             0     0   45   75445          1       1            1
 421952             0     0   45   75445          1       1            1
 421953             0     0   45   75445          1       1            1

         tiprel_1mes  indresi  indext  ...  ind_valo_fin_ult1_s  \
 40                0        1       0  ...                    0
 41                0        1       0  ...                    0
 186               0        1       0  ...                    0
 188               0        1       0  ...                    1
 189               0        1       0  ...                    1
 ...             ...      ...     ...  ...                  ...
 421949            0        1       0  ...                    0
 421950            0        1       0  ...                    0
 421951            0        1       0  ...                    0
 421952            0        1       0  ...                    0
 421953            0        1       0  ...                    0

         ind_viv_fin_ult1_s  ind_nomina_ult1_s  ind_nom_pens_ult1_s  \
 40                       0                  0                    0
 41                       0                  0                    0
 186                      0                  0                    0
 188                      0                  0                    0
 189                      0                  0                    0
 ...                    ...                ...                  ...
 421949                   0                  0                    0
 421950                   0                  0                    0
 421951                   0                  0                    0
 421952                   0                  0                    0
 421953                   0                  0                    0

         ind_recibo_ult1_s  month_int       id   y      nomprov  region
 40                      1          2    15924  19  PALMAS, LAS   north
 41                      1          7    15924  19  PALMAS, LAS   north
 186                     0          2    16162   0    BARCELONA   north
 188                     1          6    16187  14    BARCELONA   north
 189                     1          6    16187  13    BARCELONA   north
 ...                   ...        ...      ...  ..          ...     ...
 421949                  0         11  1454615   2    BARCELONA   north
 421950                  0         12  1454615  14    BARCELONA   north
 421951                  0         12  1454615  13    BARCELONA   north
 421952                  0         14  1454615  14    BARCELONA   north
 421953                  0         14  1454615  13    BARCELONA   north

 [143620 rows x 45 columns],
 'train_X_south':         ind_empleado  sexo  age   renta  ind_nuevo  indrel  indrel_1mes  \
 0                  3     0   56  326124          0       1            1
 1                  3     0   56  326124          0       1            1
 2                  3     0   56  326124          0       1            1
 3                  3     1   61  430477          0       1            1
 4                  3     1   61  430477          0       1            1
 ...              ...   ...  ...     ...        ...     ...          ...
 421937             0     1   28  118461          1       1            1
 421938             0     1   28  118461          1       1            1
 421939             0     0   41   52101          1       1            1
 421942             0     0   60   37612          1       1            1
 421947             0     0   20  175851          1       1            1

         tiprel_1mes  indresi  indext  ...  ind_tjcr_fin_ult1_s  \
 0                 0        1       0  ...                    0
 1                 0        1       0  ...                    0
 2                 0        1       0  ...                    0
 3                 0        1       0  ...                    1
 4                 0        1       0  ...                    1
 ...             ...      ...     ...  ...                  ...
 421937            0        1       1  ...                    0
 421938            0        1       1  ...                    0
 421939            0        1       0  ...                    0
 421942            0        1       0  ...                    0
 421947            0        1       0  ...                    0

         ind_valo_fin_ult1_s  ind_viv_fin_ult1_s  ind_nomina_ult1_s  \
 0                         1                   0                  0
 1                         1                   0                  0
 2                         1                   0                  0
 3                         1                   0                  0
 4                         1                   0                  0
 ...                     ...                 ...                ...
 421937                    0                   0                  0
 421938                    0                   0                  0
 421939                    0                   0                  0
 421942                    0                   0                  0
 421947                    0                   0                  0

         ind_nom_pens_ult1_s  ind_recibo_ult1_s  month_int       id  nomprov  \
 0                         0                  0          5    15889   MADRID
 1                         0                  0         12    15889   MADRID
 2                         0                  0         15    15889   MADRID
 3                         0                  1          6    15892   MADRID
 4                         0                  1          9    15892   MADRID
 ...                     ...                ...        ...      ...      ...
 421937                    0                  1         14  1454555   MADRID
 421938                    0                  1         14  1454555   MADRID
 421939                    0                  0         11  1454583   MURCIA

In [ ]:
tst = data['test_south'].copy()
product_reverse_dict = data['product_reverse_dict']   
bst = lgb.Booster(model_file='data/final/data_lightgbm/model_distributed.txt')
preds = bst.predict(tst[base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = tst
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision test_south = {test_data['apk'].mean()}")

mean average precision test_south = 0.026443885421329187

In [ ]:
tst = data['test_north'].copy()
product_reverse_dict = data['product_reverse_dict']   
bst = lgb.Booster(model_file='data/final/data_lightgbm/model_distributed.txt')
preds = bst.predict(tst[base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = tst
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision test_north = {test_data['apk'].mean()}")

mean average precision test_north = 0.017835593289980797

In [ ]:
tst = data['test'].copy()
product_reverse_dict = data['product_reverse_dict']   
bst = lgb.Booster(model_file='data/final/data_lightgbm/model_distributed.txt')
preds = bst.predict(tst[base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = tst
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision test = {test_data['apk'].mean()}")

mean average precision test = 0.022793803380779395

In [ ]:
data = get_two_region_data()
param = {
    'objective': 'multiclass',
    'num_class': 22,
    'eta': 0.05,
    'min_child_weight': 1,
    'subsample': 0.7,
    'colsample_bytree': 0.7,
    'max_depth': 8,
    'metric': 'multi_logloss',
    'verbosity': 2
}
num_round = 50
train_data = lgb.Dataset(data['train_X_north'][base_model.feature_cols], label=data['train_y_north'])
bst = lgb.train(param, train_data, num_round)

load data
prepare data

In [ ]:
preds = bst.predict(data['test'][base_model.feature_cols])
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:,:7]
preds = pd.DataFrame(preds)
preds = preds.applymap(lambda x: product_reverse_dict[x])
preds['added_products'] = preds.apply(lambda x: list(x.values), axis=1)
preds = preds['added_products']
test_data = test.copy()
target_cols = base_model.target_cols
test_data.reset_index(inplace=True)
test_data['added_products'] = preds
test_data['truth_list'] = test_data[target_cols].apply(lambda x: list(compress(target_cols, x.values)), axis=1)
test_data['apk'] = test_data.apply(lambda x: base_model.apk(x['truth_list'], x['added_products']),axis=1)
print(f"mean average precision south = {test_data['apk'].mean()}")

mean average precision south = 0.022730792975139427

In [ ]:
data.keys()

dict_keys(['product_dict', 'product_reverse_dict', 'feature_cols', 'target_cols', 'train', 'test', 'train_south', 'train_north', 'train_X_south', 'train_y_south', 'train_X_north', 'train_y_north', 'test_south', 'test_north'])

## References 

- [Mengwei Yang et.al., The Tradeoff Between Privacy and Accuracy in Anomaly Detection Using Federated XGBoost (2019)](https://arxiv.org/abs/1907.07157)
- [Yang, Federated Machine Learning: Concept and Applications (2019)](https://arxiv.org/abs/1902.04885)
- https://mc2-xgboost.readthedocs.io/en/latest/tutorials/distributed.html
- [Tianqi Chen et.al, XGBoost (2016)](https://arxiv.org/pdf/1603.02754.pdf)
- [XGBoost Distributed Training and Parallel Predictions with Apache Spark](https://medium.com/cloudzone/xgboost-distributed-training-and-predicting-with-apache-spark-1127cdfb31ae)
- InPrivate Digging: Enabling Tree-based Distributed Data Mining with Differential Privacy